spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
  redis:
    host: 192.168.56.100
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: spring:session

server:
  port: 8100
  servlet:
    session:
      timeout: 30m


