spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    alicloud:
      access-key: LTAI5tD2rqX764tTjwDXiHbb
      secret-key: tKrHnLIT0z9TrFQbFQ98iKshk0iBiL
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: eshopping-mall
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        method: POST
        appCode: cd8de5a41ea84886aad973df1b844967
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:8858
        client-ip: 192.168.56.1
  application:
    name: mall-third

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: '*'
